services:
  # Service MongoDB
  mongo:
    image: mongo:latest
    container_name: media-streaming-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # command: mongod --quiet --logpath /dev/null

volumes:
  mongo-data: